/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/hgl1p376NDz
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { CardContent, Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";
import Link from "next/link";

export function Component() {
  return (
    <>
      <header className="w-full bg-gray-100 dark:bg-gray-800 py-8 md:py-12 lg:py-16">
        <div className="container mx-auto px-4 md:px-6 lg:px-8">
          <div className="grid md:grid-cols-2 gap-8 items-center">
            <div className="space-y-4">
              <h1 className="text-3xl md:text-4xl lg:text-5xl font-bold tracking-tight">
                John Doe
              </h1>
              <h2 className="text-xl md:text-2xl lg:text-3xl font-medium text-gray-500 dark:text-gray-400">
                Software Engineer
              </h2>
              <p className="text-base md:text-lg lg:text-xl text-gray-600 dark:text-gray-300">
                I am a passionate software engineer with a strong background in
                building scalable and efficient web applications. I love
                exploring new technologies and continuously learning to improve
                my craft.
              </p>
            </div>
            <div className="flex justify-center">
              <img
                alt="John Doe"
                className="rounded-full w-48 h-48 md:w-64 md:h-64 lg:w-80 lg:h-80 object-cover"
                height={300}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "300/300",
                  objectFit: "cover",
                }}
                width={300}
              />
            </div>
          </div>
        </div>
      </header>
      <main>
        <section className="py-12 md:py-16 lg:py-20">
          <div className="container mx-auto px-4 md:px-6 lg:px-8">
            <h2 className="text-2xl md:text-3xl lg:text-4xl font-bold mb-8">
              Projects
            </h2>
            <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-6">
              <Card>
                <img
                  alt="Project 1"
                  className="w-full h-48 object-cover rounded-t-lg"
                  height={400}
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "600/400",
                    objectFit: "cover",
                  }}
                  width={600}
                />
                <CardContent className="p-4">
                  <h3 className="text-xl font-semibold mb-2">Project 1</h3>
                  <p className="text-gray-600 dark:text-gray-400">
                    A web application that helps users manage their tasks and
                    projects.
                  </p>
                </CardContent>
              </Card>
              <Card>
                <img
                  alt="Project 2"
                  className="w-full h-48 object-cover rounded-t-lg"
                  height={400}
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "600/400",
                    objectFit: "cover",
                  }}
                  width={600}
                />
                <CardContent className="p-4">
                  <h3 className="text-xl font-semibold mb-2">Project 2</h3>
                  <p className="text-gray-600 dark:text-gray-400">
                    A mobile app that allows users to track their fitness
                    activities.
                  </p>
                </CardContent>
              </Card>
              <Card>
                <img
                  alt="Project 3"
                  className="w-full h-48 object-cover rounded-t-lg"
                  height={400}
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "600/400",
                    objectFit: "cover",
                  }}
                  width={600}
                />
                <CardContent className="p-4">
                  <h3 className="text-xl font-semibold mb-2">Project 3</h3>
                  <p className="text-gray-600 dark:text-gray-400">
                    A web-based data visualization tool for analyzing complex
                    datasets.
                  </p>
                </CardContent>
              </Card>
            </div>
          </div>
        </section>
        <section className="py-12 md:py-16 lg:py-20 bg-gray-100 dark:bg-gray-800">
          <div className="container mx-auto px-4 md:px-6 lg:px-8">
            <h2 className="text-2xl md:text-3xl lg:text-4xl font-bold mb-8">
              Skills
            </h2>
            <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 gap-4">
              <Badge variant="secondary">JavaScript</Badge>
              <Badge variant="secondary">React</Badge>
              <Badge variant="secondary">Node.js</Badge>
              <Badge variant="secondary">TypeScript</Badge>
              <Badge variant="secondary">MongoDB</Badge>
              <Badge variant="secondary">SQL</Badge>
              <Badge variant="secondary">Git</Badge>
              <Badge variant="secondary">Docker</Badge>
              <Badge variant="secondary">AWS</Badge>
              <Badge variant="secondary">Kubernetes</Badge>
            </div>
          </div>
        </section>
        <section className="py-12 md:py-16 lg:py-20">
          <div className="container mx-auto px-4 md:px-6 lg:px-8">
            <h2 className="text-2xl md:text-3xl lg:text-4xl font-bold mb-8">
              Contact
            </h2>
            <form className="max-w-lg mx-auto">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div className="space-y-2">
                  <Label htmlFor="name">Name</Label>
                  <Input id="name" placeholder="Enter your name" type="text" />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="email">Email</Label>
                  <Input
                    id="email"
                    placeholder="Enter your email"
                    type="email"
                  />
                </div>
              </div>
              <div className="space-y-2 mt-6">
                <Label htmlFor="message">Message</Label>
                <Textarea
                  id="message"
                  placeholder="Enter your message"
                  rows={5}
                />
              </div>
              <div className="mt-6 flex justify-end">
                <Button type="submit">Send Message</Button>
              </div>
            </form>
          </div>
        </section>
      </main>
      <footer className="bg-gray-900 text-white py-8">
        <div className="container mx-auto px-4 md:px-6 lg:px-8 flex justify-between items-center">
          <p className="text-sm">© 2024 John Doe. All rights reserved.</p>
          <div className="flex gap-4">
            <Link className="text-gray-400 hover:text-white" href="#">
              <GithubIcon className="w-6 h-6" />
            </Link>
            <Link className="text-gray-400 hover:text-white" href="#">
              <LinkedinIcon className="w-6 h-6" />
            </Link>
            <Link className="text-gray-400 hover:text-white" href="#">
              <TwitterIcon className="w-6 h-6" />
            </Link>
          </div>
        </div>
      </footer>
    </>
  );
}

function GithubIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4" />
      <path d="M9 18c-4.51 2-5-2-7-2" />
    </svg>
  );
}

function LinkedinIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z" />
      <rect width="4" height="12" x="2" y="9" />
      <circle cx="4" cy="4" r="2" />
    </svg>
  );
}

function TwitterIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
    </svg>
  );
}
