/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/822Q76j5Jxp
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { DM_Sans } from 'next/font/google'
import { Rethink_Sans } from 'next/font/google'

dm_sans({
  subsets: ['latin'],
  display: 'swap',
})

rethink_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";
import { Button } from "@/components/ui/button";
import {
  CardTitle,
  CardDescription,
  CardContent,
  Card,
} from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";

export function Component() {
  return (
    <div className="flex flex-col min-h-screen">
      <header className="bg-gray-900 text-white py-4 px-6 md:px-12 fixed top-0 w-full z-50">
        <div className="container mx-auto flex items-center justify-between">
          <div className="flex items-center">
            <CodeIcon className="h-8 w-8 mr-2" />
            <span className="text-xl font-bold">Sumin Song</span>
          </div>
          <nav className="hidden md:flex space-x-6">
            <Link className="hover:underline" href="#">
              Home
            </Link>
            <Link className="hover:underline" href="#projects">
              Projects
            </Link>
            <Link className="hover:underline" href="#skills">
              Skills
            </Link>
            <Link className="hover:underline" href="#contact">
              Contact
            </Link>
          </nav>
          <Button className="hidden md:inline-flex" variant="outline">
            Hire Me
          </Button>
        </div>
      </header>
      <section className="bg-gray-900 text-white py-12 md:py-24">
        <div className="container mx-auto px-6 md:px-12 flex flex-col md:flex-row items-center justify-between">
          <div className="md:w-1/2 space-y-4">
            <h1 className="text-3xl md:text-4xl font-bold">Sumin Song</h1>
            <p className="text-lg md:text-xl">
              Experienced Unity Game Programmer with a passion for creating
              immersive and engaging gaming experiences.
            </p>
            <div className="flex space-x-4">
              <Link href="#projects">
                <Button variant="default">View Projects</Button>
              </Link>
              <Link href="#contact">
                <Button variant="outline">Contact Me</Button>
              </Link>
            </div>
          </div>
          <div className="md:w-1/2 mt-8 md:mt-0">
            <img
              alt="Sumin Song"
              className="rounded-lg"
              height={400}
              src="/placeholder.svg"
              style={{
                aspectRatio: "600/400",
                objectFit: "cover",
              }}
              width={600}
            />
          </div>
        </div>
      </section>
      <section className="bg-gray-100 dark:bg-gray-800 py-16 md:py-24" id="projects">
        <div className="container mx-auto px-6 md:px-12">
          <h2 className="text-2xl md:text-3xl font-bold mb-12">My Projects</h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8">
            <Card className="mb-8">
              <img
                alt="Project 1"
                className="rounded-t-lg"
                height={300}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "400/300",
                  objectFit: "cover",
                }}
                width={400}
              />
              <CardContent className="p-6">
                <CardTitle className="text-xl font-bold mb-2">Project 1</CardTitle>
                <CardDescription className="text-gray-600">
                  A captivating 3D adventure game built with Unity.
                </CardDescription>
              </CardContent>
            </Card>
            <Card className="mb-8">
              <img
                alt="Project 2"
                className="rounded-t-lg"
                height={300}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "400/300",
                  objectFit: "cover",
                }}
                width={400}
              />
              <CardContent className="p-6">
                <CardTitle className="text-xl font-bold mb-2">Project 2</CardTitle>
                <CardDescription className="text-gray-600">
                  An immersive VR experience that pushes the boundaries of gaming.
                </CardDescription>
              </CardContent>
            </Card>
            <Card className="mb-8">
              <img
                alt="Project 3"
                className="rounded-t-lg"
                height={300}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "400/300",
                  objectFit: "cover",
                }}
                width={400}
              />
              <CardContent className="p-6">
                <CardTitle className="text-xl font-bold mb-2">Project 3</CardTitle>
                <CardDescription className="text-gray-600">
                  A multiplayer online game with a unique and engaging gameplay.
                </CardDescription>
              </CardContent>
            </Card>
          </div>
        </div>
      </section>
      <section className="bg-gray-900 text-white py-12 md:py-24" id="skills">
        <div className="container mx-auto px-6 md:px-12">
          <h2 className="text-2xl md:text-3xl font-bold mb-8">My Skills</h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
            <div className="bg-gray-800 rounded-lg p-6">
              <h3 className="text-xl font-bold mb-4">Programming Languages</h3>
              <ul className="space-y-2">
                <li>C#</li>
                <li>C++</li>
                <li>C</li>
              </ul>
            </div>
            <div className="bg-gray-800 rounded-lg p-6">
              <h3 className="text-xl font-bold mb-4">Game Engines</h3>
              <ul className="space-y-2">
                <li>Unity</li>
                <li>Unreal Engine</li>
              </ul>
            </div>
            <div className="bg-gray-800 rounded-lg p-6">
              <h3 className="text-xl font-bold mb-4">Development Tools</h3>
              <ul className="space-y-2">
                <li>Visual Studio Code</li>
                <li>Git</li>
              </ul>
            </div>
          </div>
        </div>
      </section>
      <section
        className="bg-gray-100 dark:bg-gray-800 py-12 md:py-24"
        id="contact"
      >
        <div className="container mx-auto px-6 md:px-12">
          <h2 className="text-2xl md:text-3xl font-bold mb-8">Get in Touch</h2>
          <form className="max-w-md mx-auto">
            <div className="mb-4">
              <label
                className="block text-gray-700 dark:text-gray-300 font-medium mb-2"
                htmlFor="name"
              >
                Name
              </label>
              <Input id="name" placeholder="Enter your name" type="text" />
            </div>
            <div className="mb-4">
              <label
                className="block text-gray-700 dark:text-gray-300 font-medium mb-2"
                htmlFor="email"
              >
                Email
              </label>
              <Input id="email" placeholder="Enter your email" type="email" />
            </div>
            <div className="mb-4">
              <label
                className="block text-gray-700 dark:text-gray-300 font-medium mb-2"
                htmlFor="message"
              >
                Message
              </label>
              <Textarea
                id="message"
                placeholder="Enter your message"
                rows={5}
              />
            </div>
            <Button className="w-full" type="submit" variant="primary">
              Send Message
            </Button>
          </form>
        </div>
      </section>
      <footer className="bg-gray-900 text-white py-6">
        <div className="container mx-auto px-6 md:px-12 flex items-center justify-between">
          <div className="flex items-center">
            <CodeIcon className="h-6 w-6 mr-2" />
            <span className="text-lg font-bold">Sumin Song</span>
          </div>
          <div className="flex space-x-4">
            <Link className="hover:underline" href="#">
              Privacy Policy
            </Link>
            <Link className="hover:underline" href="#">
              Terms of Service
            </Link>
            <Link className="hover:underline" href="#">
              Contact
            </Link>
          </div>
        </div>
      </footer>
    </div>
  );
}

function CodeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="16 18 22 12 16 6" />
      <polyline points="8 6 2 12 8 18" />
    </svg>
  );
}
